ExtendApp/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExtendApp.Models
{
    public class Album
    {
        public string Title { get; set; }
        public List<Song> Songs { get; set; }
    }
}

ExtendApp/Models/Song.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExtendApp.Models
{
    public class Song
    {
        public string Title { get; set; }
    }
}

ExtendApp/Controllers/ModelBindingController.cs
using ExtendApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace ExtendApp.Controllers
{
    public class ModelBindingController : Controller
    {
        public Album TestAlbum => new Album
        {
            Title = "Hi",
            Songs = new List<Song>
            {
                new Song { Title = "Really good song" },
                new Song { Title = "We got more of those" },
                new Song { Title = "This one is good too" }
            }
        };

        public IActionResult MvcOnly()
        {
            return View(TestAlbum);
        }

        public IActionResult MvcAndVue()
        {
            return View(TestAlbum);
        }

        [HttpPost]
        public IActionResult CreateAlbum(Album album)
        {
            return View();
        }

        #region Vue Only 
        public IActionResult VueOnly()
        {
            return View();
        }

        public IActionResult GetVueOnlyData()
        {
            return Ok(TestAlbum);
        }

        [HttpPost]
        public IActionResult PostVueOnlyData([FromBody] Album album)
        {
            return View();
        }
        #endregion

        public IActionResult Managed()
        {
            return View();
        }
    }
}

ExtendApp/Views/ModelBinding/Managed.cshtml
@{
    Layout = "_Layout";
}

<div id="app">
    <h1>{{test}}</h1>
    <div>
        <button @@click="model.songs.push({title: ''})">Add</button>
        <button @@click="model.songs.pop()">Remove</button>
    </div>
    <input v-model="model.title" />
    <div v-for="s in model.songs">
        <input v-model="s.title" />
    </div>
    <button @@click="post()">Send iT</button>
</div>

ExtendApp/Views/ModelBinding/MvcAndVue.cshtml
@model ExtendApp.Models.Album
@*
    Main thing to keep in mind here:
    1. The server will render the page
    2. Vue will load the div#app section
    3. Vue will re-render the section it has loaded
    4. State can be lost where vue touches the element tree
        - it's safe to assume that it will be lost, so code around it
*@

<h1>Mvc And Vue Example</h1>

<div id="app">
    <form asp-controller="ModelBinding" asp-action="CreateAlbum" method="post">
        <p>
            <button type="button" @@click="rows.push({index: rows.length, title: ''})">Add</button>
            <button type="button" @@click="rows.pop()">Remove</button>
        </p>
        <input asp-for="@Model.Title" />
        <div v-for="row in rows">
            <input :name="`Songs[${row.index}].Title`" v-model="row.title" />
        </div>

        <button type="submit">Send iT</button>
    </form>
</div>



@* How to transfer model state? *@
@{
    var json_state = Model.Songs.Select((x, i) => new { index = i, title = x.Title });
}
<script>
    var __state__ = @Html.Raw(System.Text.Json.JsonSerializer.Serialize(json_state))
</script>



@{
    @*if using render script section put this in there too*@
    await Html.RenderPartialAsync("_VueJs");
}



@*can use render script section here*@
<script src="~/notmanaged/mvc_and_vue.js"></script>

ExtendApp/Views/ModelBinding/MvcOnly.cshtml
@model ExtendApp.Models.Album

@*
    Safe space for simple forms, complexity occurs when js/jquery need to be involved    
*@

<h1>Mvc Only Example</h1>

<form asp-controller="ModelBinding" asp-action="CreateAlbum">
    <input asp-for="@Model.Title" />
    <div>
        <input asp-for="@Model.Songs[0].Title" />
    </div>
    <div>
        <input asp-for="@Model.Songs[1].Title" />
    </div>
    <div>
        <input asp-for="@Model.Songs[2].Title" />
    </div>

    <button type="submit">Send iT</button>
</form>

<script>
    // js magic here
</script>

ExtendApp/Views/ModelBinding/VueOnly.cshtml
<h1>Vue Only Example</h1>

@*
    Safe space for crafting complex forms, however more manual ui handling has to be done here.
*@

<div id="app">
    <div>
        <button @@click="model.songs.push({title: ''})">Add</button>
        <button @@click="model.songs.pop()">Remove</button>
    </div>
    <input v-model="model.title" />
    <div v-for="s in model.songs">
        <input v-model="s.title" />
    </div>
    <button @@click="post()">Send iT</button>
</div>

@{
    @* if using render script section put this in there too *@
    await Html.RenderPartialAsync("_VueJs");
}
 
@* http client or use the fetch api *@
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

@* can use render script section here *@
<script src="~/notmanaged/vue_only.js"></script>

ExtendApp/Views/Shared/_Layout.cshtml
@{
    var controllerName = ViewContext.RouteData.Values["controller"].ToString();
    var actionName = ViewContext.RouteData.Values["action"].ToString();
    var jsFile = string.Concat("/dist/js/", controllerName, "_", actionName, ".js");
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>


    @{
        await Html.RenderPartialAsync("_VueJs");
    }

    <script src="@jsFile"></script>

</body>
</html>

ExtendApp/Views/Shared/_VueJs.cshtml
<script src="https://cdn.jsdelivr.net/npm/vue"></script>